$(document).ready(function(){
	$('*.fp').click(function(){
		$('.maindiv').show();
		$('.popup').show();
	});
});
$(window).load(function() 
		{
			if ($('.popup').find('.error').length) 
			{
				$('.maindiv').show();
				$('.popup').show();
			}
		});
$(document).ready(function(){
	$('.close').click(function(){
		$('.maindiv').hide();
		$('.popup').hide();
	});
});